# Generated by Django 5.2.11 on 2026-03-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='learningunit',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['not_started', 'in_progress', 'completed'])), name='chk_status_valid'),
        ),
    ]
