# Generated by Django 5.2.11 on 2026-03-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_learningunit_chk_status_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunit',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
