# Generated by Django 5.2.11 on 2026-03-17 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_learningunit_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='learningunit',
            unique_together=set(),
        ),
    ]
