# Generated by Django 5.2.11 on 2026-03-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_learningunit_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
