# Generated by Django 5.2.11 on 2026-03-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_learningresource_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningresource',
            name='url',
            field=models.URLField(blank=True, help_text='Optional link to the resource'),
        ),
    ]
