# Generated by Django 5.2.11 on 2026-03-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_alter_learningresource_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunit',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='How many minutes the video is in total.', null=True, verbose_name='Total Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='video_progress_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='How many minutes of the video have been watched.', null=True, verbose_name='Progress Watched (minutes)'),
        ),
        migrations.AddConstraint(
            model_name='learningunit',
            constraint=models.CheckConstraint(condition=models.Q(('video_progress_minutes__lte', models.F('duration_minutes')), ('video_progress_minutes__isnull', True), ('duration_minutes__isnull', True), _connector='OR'), name='chk_progress_lte_duration'),
        ),
    ]
