# Generated by Django 5.2.11 on 2026-03-22 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_alter_learningunit_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningresource',
            options={'ordering': ['-created_at'], 'permissions': [('view_dashboard', 'Can view the dashboard with learning statistics')]},
        ),
    ]
