# Generated by Django 5.2.11 on 2026-03-22 22:43

from django.db import migrations


def create_learning_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    group, _ = Group.objects.get_or_create(name="Learning User")

    permissions = Permission.objects.filter(
        content_type__app_label="learning",
        codename__in=[
            "view_learningresource",
            "add_learningresource",
            "change_learningresource",
            "delete_learningresource",
            "view_learningunit",
            "add_learningunit",
            "change_learningunit",
            "delete_learningunit",
            "view_dashboard",
        ],
    )

    group.permissions.set(permissions)


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0008_alter_learningresource_options"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(create_learning_group),
    ]
