# Generated by Django 5.2.11 on 2026-03-26 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_create_learning_group'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='learningresource',
            table='learning_resource',
        ),
        migrations.AlterModelTable(
            name='learningunit',
            table='learning_unit',
        ),
    ]
