# Generated by Django 5.2.11 on 2026-05-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_finalise_resource_type_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
